# Generated by Django 5.0.7 on 2024-07-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
