name: Unit Testing
on: push

jobs:
    Test_project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Django unit tests
              run: |
                  python -m pip install -r requirements.txt
                  run: ./final_project/manage.py test
